---

- hosts: all
  become: true
  tasks:

  - name: install httpd package
    yum: 
       name: httpd
    when: ansible_distribution == "dbian"
       
  - name: install apache
    yum: 
        name: apache

